// File: seed.js atau di dalam API route
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedConsultations() {
  try {
    const consultations = await prisma.consultation.createMany({
      data: [
        {
          // Data 1 - Tanggal 1 Januari 2024
          tanggal: "2024-01-01",
          waktu: "09:00",
          nama: "Ahmad Rizki",
          instansi: "Kementerian PUPR",
          jabatan: "Kepala Bagian Pengadaan",
          alamat: "Jl. Pattimura No. 20, Jakarta Selatan",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "081234567890",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-001-2024",
          namaPaketPengadaan: "Pengadaan Jaringan Internet Fiber Optic",
          nilaiKontrak: "2500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Tahun Berjalan",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Jakarta Pusat",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Terdapat ketidaksesuaian dalam klausul kontrak pengadaan",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gMTwvdGV4dD48L3N2Zz4=",
          status: "SUBMITTED",
          isLocked: true,
        },
        {
          // Data 2 - Tanggal 5 Januari 2024
          tanggal: "2024-01-05",
          waktu: "14:30",
          nama: "Siti Nurhaliza",
          instansi: "Pemerintah Provinsi Jawa Barat",
          jabatan: "Staf Pengadaan",
          alamat: "Jl. Merdeka No. 45, Bandung",
          provinsiPemohon: "Jawa Barat",
          noTelp: "082345678901",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-002-2024",
          namaPaketPengadaan: "Pembangunan Gedung Sekolah Dasar",
          nilaiKontrak: "5000000000",
          TTDKontrak: false,
          kontrak: "Kontrak Baru",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kabupaten Bandung",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Seleksi",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Kendala teknis dalam spesifikasi teknis pengadaan",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gMjwvdGV4dD48L3N2Zz4=",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 3 - Tanggal 10 Januari 2024
          tanggal: "2024-01-10",
          waktu: "10:15",
          nama: "Budi Santoso",
          instansi: "Kementerian Kesehatan",
          jabatan: "Koordinator Pengadaan",
          alamat: "Jl. HR Rasuna Said Kav. X-5, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "083456789012",
          jumlahTamu: 3,
          idPaketPengadaan: "PKD-003-2024",
          namaPaketPengadaan: "Pengadaan Alat Kesehatan",
          nilaiKontrak: "1500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Perpanjangan",
          jenisKontrak: "Gabungan",
          wilayahPengadaan: "Jakarta Selatan",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Pengadaan Langsung",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen administrasi tidak lengkap",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gMzwvdGV4dD48L3N2Zz4=",
          status: "COMPLETED",
          isLocked: true,
        },
        {
          // Data 4 - Tanggal 15 Januari 2024
          tanggal: "2024-01-15",
          waktu: "13:45",
          nama: "Maya Sari",
          instansi: "Pemerintah Kota Surabaya",
          jabatan: "Analis Pengadaan",
          alamat: "Jl. Tunjungan No. 1, Surabaya",
          provinsiPemohon: "Jawa Timur",
          noTelp: "084567890123",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-004-2024",
          namaPaketPengadaan: "Penyediaan Jasa Konsultan",
          nilaiKontrak: "750000000",
          TTDKontrak: true,
          kontrak: "Kontrak Berlanjut",
          jenisKontrak: "Waktu dan Material",
          wilayahPengadaan: "Kota Surabaya",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Jasa Konsultansi",
          metodePemilihan: "Penunjukan Langsung",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Penafsiran klausul kontrak yang berbeda",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gNDwvdGV4dD48L3N2Zz4=",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 5 - Tanggal 20 Januari 2024
          tanggal: "2024-01-20",
          waktu: "11:00",
          nama: "Rizki Pratama",
          instansi: "Kementerian Pendidikan",
          jabatan: "Kepala Sub Bagian",
          alamat: "Jl. Jenderal Sudirman No. 102, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "085678901234",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-005-2024",
          namaPaketPengadaan: "Pengadaan Buku Pelajaran",
          nilaiKontrak: "1200000000",
          TTDKontrak: false,
          kontrak: "Kontrak Baru",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Jakarta Pusat",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Spesifikasi teknis tidak sesuai kebutuhan",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gNTwvdGV4dD48L3N2Zz4=",
          status: "REJECTED",
          isLocked: true,
        },
        {
          // Data 6 - Tanggal 25 Januari 2024
          tanggal: "2024-01-25",
          waktu: "15:30",
          nama: "Dewi Lestari",
          instansi: "Pemerintah Provinsi Bali",
          jabatan: "Staf Hukum",
          alamat: "Jl. Majapahit No. 1, Denpasar",
          provinsiPemohon: "Bali",
          noTelp: "086789012345",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-006-2024",
          namaPaketPengadaan: "Pembangunan Infrastruktur Pariwisata",
          nilaiKontrak: "8000000000",
          TTDKontrak: true,
          kontrak: "Kontrak Tahun Berjalan",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kabupaten Badung",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Administratif",
          kronologi: "Proses administrasi pengadaan yang tertunda",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qob4=",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 7 - Tanggal 1 Februari 2024
          tanggal: "2024-02-01",
          waktu: "09:45",
          nama: "Hendra Wijaya",
          instansi: "Kementerian Perhubungan",
          jabatan: "Manager Proyek",
          alamat: "Jl. Medan Merdeka Barat No. 8, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "087890123456",
          jumlahTamu: 4,
          idPaketPengadaan: "PKD-007-2024",
          namaPaketPengadaan: "Pengadaan Sistem Transportasi",
          nilaiKontrak: "12000000000",
          TTDKontrak: true,
          kontrak: "Kontrak Besar",
          jenisKontrak: "Gabungan",
          wilayahPengadaan: "Jakarta Utara",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Seleksi",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Force majeure dalam pelaksanaan kontrak",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gNzwvdGV4dD48L3N2Zz4=",
          status: "COMPLETED",
          isLocked: true,
        },
        {
          // Data 8 - Tanggal 5 Februari 2024
          tanggal: "2024-02-05",
          waktu: "14:00",
          nama: "Lina Marlina",
          instansi: "Pemerintah Kota Medan",
          jabatan: "Koordinator Proyek",
          alamat: "Jl. Diponegoro No. 22, Medan",
          provinsiPemohon: "Sumatera Utara",
          noTelp: "088901234567",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-008-2024",
          namaPaketPengadaan: "Pengadaan Peralatan Kantor",
          nilaiKontrak: "350000000",
          TTDKontrak: false,
          kontrak: "Kontrak Kecil",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kota Medan",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Barang",
          metodePemilihan: "Pengadaan Langsung",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Spesifikasi produk tidak tersedia di pasar",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gODwvdGV4dD48L3N2Zz4=",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 9 - Tanggal 10 Februari 2024
          tanggal: "2024-02-10",
          waktu: "10:30",
          nama: "Fajar Nugroho",
          instansi: "Kementerian ESDM",
          jabatan: "Supervisor Pengadaan",
          alamat: "Jl. Gatot Subroto Kav. 49, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "089012345678",
          jumlahTamu: 3,
          idPaketPengadaan: "PKD-009-2024",
          namaPaketPengadaan: "Pengadaan Peralatan Energi",
          nilaiKontrak: "4500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Strategis",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Jakarta Selatan",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen penawaran tidak memenuhi syarat",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gOTwvdGV4dD48L3N2Zz4=",
          status: "SUBMITTED",
          isLocked: true,
        },
        {
          // Data 10 - Tanggal 15 Februari 2024
          tanggal: "2024-02-15",
          waktu: "16:15",
          nama: "Nina Permata",
          instansi: "Pemerintah Provinsi DIY",
          jabatan: "Analis Hukum",
          alamat: "Jl. Malioboro No. 1, Yogyakarta",
          provinsiPemohon: "DI Yogyakarta",
          noTelp: "081112223344",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-010-2024",
          namaPaketPengadaan: "Pengadaan Jasa Kebersihan",
          nilaiKontrak: "280000000",
          TTDKontrak: true,
          kontrak: "Kontrak Rutin",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kota Yogyakarta",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Jasa Lainnya",
          metodePemilihan: "Penunjukan Langsung",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Wanprestasi dalam pelaksanaan kontrak",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UYW5kYSBUYW5nYW4gMTA8L3RleHQ+PC9zdmc+",
          status: "COMPLETED",
          isLocked: true,
        },
        {
          // Data 11 - Tanggal 20 Februari 2024
          tanggal: "2024-02-20",
          waktu: "08:30",
          nama: "Rudi Hermawan",
          instansi: "Kementerian Pertanian",
          jabatan: "Kepala Bidang Pengadaan",
          alamat: "Jl. Harsono RM No. 3, Ragunan, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "081223344556",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-011-2024",
          namaPaketPengadaan: "Pengadaan Bibit Tanaman Pangan",
          nilaiKontrak: "950000000",
          TTDKontrak: true,
          kontrak: "Kontrak Musiman",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Jawa Barat",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Kualitas bibit tidak sesuai spesifikasi teknis",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDExPC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 12 - Tanggal 25 Februari 2024
          tanggal: "2024-02-25",
          waktu: "13:20",
          nama: "Sari Indah",
          instansi: "Pemerintah Kota Makassar",
          jabatan: "Staf Pengelola Pengadaan",
          alamat: "Jl. Jenderal Urip Sumoharjo No. 25, Makassar",
          provinsiPemohon: "Sulawesi Selatan",
          noTelp: "082334455667",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-012-2024",
          namaPaketPengadaan: "Pembangunan Taman Kota",
          nilaiKontrak: "3200000000",
          TTDKontrak: false,
          kontrak: "Kontrak Pembangunan",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kota Makassar",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Seleksi",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen lelang tidak lengkap dan butuh verifikasi",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDEyPC90ZXh0Pjwvc3ZnPg==",
          status: "REJECTED",
          isLocked: true,
        },
        {
          // Data 13 - Tanggal 1 Maret 2024
          tanggal: "2024-03-01",
          waktu: "10:45",
          nama: "Agus Setiawan",
          instansi: "Kementerian Kelautan dan Perikanan",
          jabatan: "Koordinator Proyek",
          alamat: "Jl. Medan Merdeka Timur No. 16, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "083445566778",
          jumlahTamu: 3,
          idPaketPengadaan: "PKD-013-2024",
          namaPaketPengadaan: "Pengadaan Kapal Penangkap Ikan",
          nilaiKontrak: "12500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Besar",
          jenisKontrak: "Gabungan",
          wilayahPengadaan: "Lampung",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Klausul garansi dan maintenance tidak jelas",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDEzPC90ZXh0Pjwvc3ZnPg==",
          status: "APPROVED",
          isLocked: true,
        },
        {
          // Data 14 - Tanggal 5 Maret 2024
          tanggal: "2024-03-05",
          waktu: "14:15",
          nama: "Mira Handayani",
          instansi: "Pemerintah Provinsi Sumatera Barat",
          jabatan: "Analis Pengadaan",
          alamat: "Jl. Khatib Sulaiman No. 1, Padang",
          provinsiPemohon: "Sumatera Barat",
          noTelp: "084556677889",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-014-2024",
          namaPaketPengadaan: "Pembangunan Jalan Provinsi",
          nilaiKontrak: "18500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Multi Years",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kabupaten Tanah Datar",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Spesifikasi material jalan tidak sesuai standar",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDE0PC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 15 - Tanggal 10 Maret 2024
          tanggal: "2024-03-10",
          waktu: "09:00",
          nama: "Bambang Sugianto",
          instansi: "Kementerian BUMN",
          jabatan: "Manager Pengadaan",
          alamat: "Jl. Medan Merdeka Selatan No. 13, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "085667788990",
          jumlahTamu: 4,
          idPaketPengadaan: "PKD-015-2024",
          namaPaketPengadaan: "Pengadaan Sistem IT Perusahaan",
          nilaiKontrak: "7500000000",
          TTDKontrak: false,
          kontrak: "Kontrak Teknologi",
          jenisKontrak: "Waktu dan Material",
          wilayahPengadaan: "Jakarta Pusat",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Jasa Konsultansi",
          metodePemilihan: "Seleksi",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen penawaran teknis tidak memenuhi syarat",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDE1PC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 16 - Tanggal 15 Maret 2024
          tanggal: "2024-03-15",
          waktu: "16:30",
          nama: "Wulan Sari",
          instansi: "Pemerintah Kota Semarang",
          jabatan: "Staf Hukum dan Pengadaan",
          alamat: "Jl. Pemuda No. 148, Semarang",
          provinsiPemohon: "Jawa Tengah",
          noTelp: "086778899001",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-016-2024",
          namaPaketPengadaan: "Pengadaan Kendaraan Dinas",
          nilaiKontrak: "2800000000",
          TTDKontrak: true,
          kontrak: "Kontrak Standar",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kota Semarang",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Barang",
          metodePemilihan: "Pengadaan Langsung",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Klausul after sales service perlu penyesuaian",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDE2PC90ZXh0Pjwvc3ZnPg==",
          status: "APPROVED",
          isLocked: true,
        },
        {
          // Data 17 - Tanggal 20 Maret 2024
          tanggal: "2024-03-20",
          waktu: "11:45",
          nama: "Feri Kurniawan",
          instansi: "Kementerian Pariwisata",
          jabatan: "Kepala Seksi Pengadaan",
          alamat: "Jl. Sisingamangaraja No. 2, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "087889900112",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-017-2024",
          namaPaketPengadaan: "Pengadaan Media Promosi Pariwisata",
          nilaiKontrak: "650000000",
          TTDKontrak: true,
          kontrak: "Kontrak Kreatif",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Bali",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Jasa Lainnya",
          metodePemilihan: "Penunjukan Langsung",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Konsep kreatif tidak sesuai dengan brief awal",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDE3PC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 18 - Tanggal 25 Maret 2024
          tanggal: "2024-03-25",
          waktu: "15:00",
          nama: "Diana Puspita",
          instansi: "Pemerintah Provinsi Kalimantan Timur",
          jabatan: "Analis Hukum Pengadaan",
          alamat: "Jl. Jenderal Sudirman No. 1, Samarinda",
          provinsiPemohon: "Kalimantan Timur",
          noTelp: "088990011223",
          jumlahTamu: 3,
          idPaketPengadaan: "PKD-018-2024",
          namaPaketPengadaan: "Pembangunan Puskesmas",
          nilaiKontrak: "4200000000",
          TTDKontrak: false,
          kontrak: "Kontrak Pembangunan",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kabupaten Kutai Kartanegara",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Administratif",
          kronologi: "Izin bangunan belum lengkap menghambat proses",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDE4PC90ZXh0Pjwvc3ZnPg==",
          status: "REJECTED",
          isLocked: true,
        },
        {
          // Data 19 - Tanggal 30 Maret 2024
          tanggal: "2024-03-30",
          waktu: "10:00",
          nama: "Eko Prasetyo",
          instansi: "Kementerian Perindustrian",
          jabatan: "Supervisor Proyek",
          alamat: "Jl. Gatot Subroto Kav. 52-53, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "089001122334",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-019-2024",
          namaPaketPengadaan: "Pengadaan Mesin Industri",
          nilaiKontrak: "18500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Import",
          jenisKontrak: "Gabungan",
          wilayahPengadaan: "Jawa Timur",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender Internasional",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Klausul bea masuk dan pajak import perlu peninjauan",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDE5PC90ZXh0Pjwvc3ZnPg==",
          status: "APPROVED",
          isLocked: true,
        },
        {
          // Data 20 - Tanggal 5 April 2024
          tanggal: "2024-04-05",
          waktu: "14:45",
          nama: "Gita Maharani",
          instansi: "Pemerintah Kota Palembang",
          jabatan: "Koordinator Pengadaan",
          alamat: "Jl. Jenderal Sudirman No. 1, Palembang",
          provinsiPemohon: "Sumatera Selatan",
          noTelp: "081112223355",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-020-2024",
          namaPaketPengadaan: "Pengadaan Peralatan Olahraga",
          nilaiKontrak: "890000000",
          TTDKontrak: false,
          kontrak: "Kontrak Kecil",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kota Palembang",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Barang",
          metodePemilihan: "Pengadaan Langsung",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Spesifikasi peralatan tidak sesuai standar nasional",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDIwPC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 21 - Tanggal 10 April 2024
          tanggal: "2024-04-10",
          waktu: "09:30",
          nama: "Hadi Susanto",
          instansi: "Kementerian Lingkungan Hidup",
          jabatan: "Kepala Bagian",
          alamat: "Jl. DI Panjaitan Kav. 24, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "082223334466",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-021-2024",
          namaPaketPengadaan: "Pengadaan Alat Monitoring Lingkungan",
          nilaiKontrak: "3200000000",
          TTDKontrak: true,
          kontrak: "Kontrak Teknis",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Jakarta Utara",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Seleksi",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen kalibrasi alat belum lengkap",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDIxPC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 22 - Tanggal 15 April 2024
          tanggal: "2024-04-15",
          waktu: "13:00",
          nama: "Indra Permana",
          instansi: "Pemerintah Provinsi Nusa Tenggara Barat",
          jabatan: "Staf Pengadaan",
          alamat: "Jl. Pejanggik No. 1, Mataram",
          provinsiPemohon: "Nusa Tenggara Barat",
          noTelp: "083334445577",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-022-2024",
          namaPaketPengadaan: "Pembangunan Sarana Air Bersih",
          nilaiKontrak: "7500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Infrastruktur",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kabupaten Lombok Utara",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Klausul maintenance jangka panjang perlu review",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDIyPC90ZXh0Pjwvc3ZnPg==",
          status: "APPROVED",
          isLocked: true,
        },
        {
          // Data 23 - Tanggal 20 April 2024
          tanggal: "2024-04-20",
          waktu: "16:20",
          nama: "Joko Widodo",
          instansi: "Kementerian Sosial",
          jabatan: "Manager Program",
          alamat: "Jl. Salemba Raya No. 28, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "084445556688",
          jumlahTamu: 3,
          idPaketPengadaan: "PKD-023-2024",
          namaPaketPengadaan: "Pengadaan Bantuan Sosial",
          nilaiKontrak: "12500000000",
          TTDKontrak: false,
          kontrak: "Kontrak Sosial",
          jenisKontrak: "Gabungan",
          wilayahPengadaan: "Jawa Tengah",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Penunjukan Langsung",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Mekanisme distribusi bantuan perlu evaluasi",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDIzPC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 24 - Tanggal 25 April 2024
          tanggal: "2024-04-25",
          waktu: "11:10",
          nama: "Kartika Sari",
          instansi: "Pemerintah Kota Banjarmasin",
          jabatan: "Analis Pengadaan",
          alamat: "Jl. Lambung Mangkurat No. 1, Banjarmasin",
          provinsiPemohon: "Kalimantan Selatan",
          noTelp: "085556667799",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-024-2024",
          namaPaketPengadaan: "Pengadaan Sistem Drainase",
          nilaiKontrak: "5800000000",
          TTDKontrak: true,
          kontrak: "Kontrak Pembangunan",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kota Banjarmasin",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen AMDAL belum lengkap",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDI0PC90ZXh0Pjwvc3ZnPg==",
          status: "REJECTED",
          isLocked: true,
        },
        {
          // Data 25 - Tanggal 30 April 2024
          tanggal: "2024-04-30",
          waktu: "15:45",
          nama: "Lukman Hakim",
          instansi: "Kementerian Komunikasi dan Informatika",
          jabatan: "Kepala Sub Bidang",
          alamat: "Jl. Medan Merdeka Barat No. 9, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "086667778800",
          jumlahTamu: 4,
          idPaketPengadaan: "PKD-025-2024",
          namaPaketPengadaan: "Pengadaan Server dan Storage",
          nilaiKontrak: "9500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Teknologi",
          jenisKontrak: "Waktu dan Material",
          wilayahPengadaan: "Jakarta Pusat",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Barang",
          metodePemilihan: "Seleksi",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Klausul service level agreement perlu negosiasi",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWaldC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSI+RGF0YSAyNTwvdGV4dD48L3N2Zz4=",
          status: "APPROVED",
          isLocked: true,
        },
        {
          // Data 26 - Tanggal 5 Mei 2024
          tanggal: "2024-05-05",
          waktu: "10:30",
          nama: "Maya Permatasari",
          instansi: "Pemerintah Provinsi Papua",
          jabatan: "Staf Pengadaan",
          alamat: "Jl. Soa Siu Dok II No. 1, Jayapura",
          provinsiPemohon: "Papua",
          noTelp: "087778889911",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-026-2024",
          namaPaketPengadaan: "Pengadaan Peralatan Kesehatan Daerah Terpencil",
          nilaiKontrak: "4200000000",
          TTDKontrak: false,
          kontrak: "Kontrak Khusus",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Kabupaten Jayawijaya",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Barang",
          metodePemilihan: "Pengadaan Langsung",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi:
            "Spesifikasi alat kesehatan perlu penyesuaian kondisi daerah",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDI2PC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 27 - Tanggal 10 Mei 2024
          tanggal: "2024-05-10",
          waktu: "14:00",
          nama: "Nugroho Pratama",
          instansi: "Kementerian Perdagangan",
          jabatan: "Koordinator Pengadaan",
          alamat: "Jl. M.I. Ridwan Rais No. 5, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "088889990022",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-027-2024",
          namaPaketPengadaan: "Pengadaan Sistem E-Commerce",
          nilaiKontrak: "6800000000",
          TTDKontrak: true,
          kontrak: "Kontrak Digital",
          jenisKontrak: "Gabungan",
          wilayahPengadaan: "Jakarta Selatan",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Jasa Konsultansi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen spesifikasi teknis perlu revisi",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDI3PC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 28 - Tanggal 15 Mei 2024
          tanggal: "2024-05-15",
          waktu: "09:15",
          nama: "Oki Setiawan",
          instansi: "Pemerintah Kota Manado",
          jabatan: "Analis Hukum",
          alamat: "Jl. Sam Ratulangi No. 1, Manado",
          provinsiPemohon: "Sulawesi Utara",
          noTelp: "089990011033",
          jumlahTamu: 3,
          idPaketPengadaan: "PKD-028-2024",
          namaPaketPengadaan: "Pembangunan Pasar Tradisional",
          nilaiKontrak: "12500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Pembangunan",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kota Manado",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Konstruksi",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Hukum Kontrak",
          kronologi: "Klausul pembayaran progresif perlu penyesuaian",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDI4PC90ZXh0Pjwvc3ZnPg==",
          status: "APPROVED",
          isLocked: true,
        },
        {
          // Data 29 - Tanggal 20 Mei 2024
          tanggal: "2024-05-20",
          waktu: "16:45",
          nama: "Putri Anggraini",
          instansi: "Kementerian Koperasi dan UKM",
          jabatan: "Manager Proyek",
          alamat: "Jl. H.R. Rasuna Said Kav. 3-4, Jakarta",
          provinsiPemohon: "DKI Jakarta",
          noTelp: "081100220033",
          jumlahTamu: 2,
          idPaketPengadaan: "PKD-029-2024",
          namaPaketPengadaan: "Pengadaan Pelatihan UMKM",
          nilaiKontrak: "850000000",
          TTDKontrak: false,
          kontrak: "Kontrak Jasa",
          jenisKontrak: "Lumpsum",
          wilayahPengadaan: "Jawa Barat",
          sumberAnggaran: "APBN",
          jenisPengadaan: "Jasa Lainnya",
          metodePemilihan: "Penunjukan Langsung",
          jenisPermasalahan: "Teknis Pengadaan",
          kronologi: "Kurikulum pelatihan perlu penyesuaian kebutuhan UMKM",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI40MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDI5PC90ZXh0Pjwvc3ZnPg==",
          status: "SUBMITTED",
          isLocked: false,
        },
        {
          // Data 30 - Tanggal 25 Mei 2024
          tanggal: "2024-05-25",
          waktu: "11:30",
          nama: "Rina Marlina",
          instansi: "Pemerintah Provinsi Maluku",
          jabatan: "Staf Pengadaan",
          alamat: "Jl. Dr. Latumeten No. 1, Ambon",
          provinsiPemohon: "Maluku",
          noTelp: "082211330044",
          jumlahTamu: 1,
          idPaketPengadaan: "PKD-030-2024",
          namaPaketPengadaan: "Pengadaan Perahu Penyeberangan",
          nilaiKontrak: "3500000000",
          TTDKontrak: true,
          kontrak: "Kontrak Transportasi",
          jenisKontrak: "Harga Satuan",
          wilayahPengadaan: "Kepulauan Lease",
          sumberAnggaran: "APBD",
          jenisPengadaan: "Barang",
          metodePemilihan: "Tender",
          jenisPermasalahan: "Administratif",
          kronologi: "Dokumen keselamatan kapal perlu kelengkapan",
          signatureData:
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB2aWV3Qm94PSIwIDAgMjAwIDgwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjZjNmM2YzIi8+PHRleHQgeD0iMTAwIiB5PSI0MCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjOTk5IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYXRhIDMwPC90ZXh0Pjwvc3ZnPg==",
          status: "APPROVED",
          isLocked: true,
        },
      ],
    });

    console.log(`Berhasil menambahkan ${consultations.count} data konsultasi`);
  } catch (error) {
    console.error("Error seeding consultations:", error);
  } finally {
    await prisma.$disconnect();
  }
}

// Jalankan fungsi
seedConsultations();
